HOME=/home/desingh
LIBEMPI_DIR=/home/desingh/FlexMPI
PAPI_DIR=$(HOME)/LIBS/papi
GLPK_DIR=$(HOME)/LIBS/glpk
MPICC=$(HOME)/LIBS/mpich/bin/mpicc


PAPI=-I$(PAPI_DIR)/include/ -lpapi -L$(PAPI_DIR)/lib -lpfm
GLPK=-I$(GLPK_DIR)/include/  -L$(GLPK_DIR)/lib/ -lglpk 
EMPI=-I$(LIBEMPI_DIR)/include/ -L$(LIBEMPI_DIR)/lib/ -I$(LIBEMPI_DIR)/include -lempi -lmpi 
CFLAGS=-Wall -g
MATH= -lm

.PHONY: jacobi gradient
	
jacobi:

	$(MPICC) $(CFLAGS) -o jacobi_IO_V4.o jacobi_IO_V4.c -c $(EMPI) $(PAPI) $(GLPK) 
	$(MPICC) $(CFLAGS)  jacobi_IO_V4.o -o jacobi_IO  $(EMPI) $(PAPI) $(GLPK) 
